version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dify-postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: dify-redis
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: langgenius/dify-api:latest
    container_name: dify-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5001:5001"

  web:
    image: langgenius/dify-web:latest
    container_name: dify-web
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api

  worker:
    image: langgenius/dify-worker:latest
    container_name: dify-worker
    restart: always
    depends_on:
      - api
    env_file:
      - .env

volumes:
  pg_data:
  redis_data:
